#!/usr/bin/env bash
#
# Summary: Display the version of jlenv
#
# Usage: jlenv [<opts>] --version
#
# Displays the version number of this jlenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#
#    <semver>-<num_commits>-<git_sha>
#
# where `num_commits` is the number of commits since the semantic version
# number `semver` was tagged.

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

git_revision=""

cd "${jlenv_dirname%/*}"

jlenv_check="$( git remote -v 2>/dev/null | grep \/jlenv\/ 2>/dev/null )"
  if [[ -n "${jlenv_check}" ]]; then
    git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
    git_revision="${git_revision#v}"
  fi

cd - 1>/dev/null 2>&1

echo "jlenv ${git_revision:-"not.jlenv.version"}"
