#!/usr/bin/env bash
jlenv_commands()
# List all available jlenv commands
#
# Usage: jlenv commands [-n -s]
#
# Produce a list of jlenv commands.  This is used internally to provide
# shell <tab>-completion.
#
# Options:
#  -g   List those generic commands.
#  -s   List those shell specific commands.
#
# See also:  jlenv2 complete
{

  # TODO Options (see jlenv-version)
  # [c]ron, [n]o-color, [v]erbose
  gsu_getopts 'gs'
  eval "$result"
  ((ret < 0)) && return

if [ "$o_s" = "true" ]; then
  sh=1
  shift
elif [ "$o_g" = "true" ]; then
  nosh=1
  shift
fi

com_complete 1 2>/dev/null 1>&2
IFS=" " command=($result)

shopt -s nullglob

{ for command in "${command[@]}"; do
    if [ -n "$sh" ]; then
      if [ ${command:0:3} = "sh-" ]; then
        echo ${command##sh-}
      fi
    elif [ -n "$nosh" ]; then
      if [ ${command:0:3} != "sh-" ]; then
        echo ${command##sh-}
      fi
    else
      echo ${command##sh-}
    fi
  done
} 
}
complete_commands()
{
  local optstring='nv'
  gsu_complete_options $optstring "$@"
  ((ret > 0)) && return
  gsu_cword_is_option_parameter $optstring "$@"
}