#!/usr/bin/env bash
# Usage: jlenv version-file [<dir>]
# Summary: Detect the file that sets the current jlenv version

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -e "${root}/.julia-version" ]; then
      echo "${root}/.julia-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$JLENV_DIR" || {
    [ "$JLENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${JLENV_ROOT}/version"
fi
