#!/usr/bin/env bash
jlenv_version()
##
##
## Show the current Julia version and how it was selected.
##
## Usage: jlenv version []
##
## To obtain only the version string, use $(jlenv version-name).
## Any arguments to this function are ignored.
##
## Options:
##
##      -v: Enable verbose mode
##      -c: Enable cron mode
##      -n: Enable no-color mode
##
{
  # No arguments allowed
  gsu_check_arg_count $# 0 0 
  # gsu_err_msg "${result}"
  ((ret < 0)) && return
  
  # Options
  # [c]ron, [n]o-color, [v]erbose
  gsu_getopts 'cnv'
  eval "$result"
  ((ret < 0)) && return

  # The verbose option variable
  if [ "$o_v" = 'true' ]; then
    printf '%s (set by %s)\n' "$(com_version-name)" "$(com_version-origin)"
  else
    printf '%s (set by %s)\n' "$(com_version-name)" "$(com_version-origin)"
  fi
}

complete_version()
{
  local optstring='cnv'
  gsu_complete_options $optstring "$@"
  ((ret > 0)) && return
  gsu_cword_is_option_parameter $optstring "$@"
}