#!/usr/bin/env bash
jlenv_local()
## Summary: Set or show the local application-specific Julia version
##
## Usage: jlenv local <version>
##        jlenv local --unset
##
## Sets the local application-specific Julia version by writing the
## version name to a file named `.julia-version'.
##
## When you run a Julia command, jlenv will look for a `.julia-version'
## file in the current directory and each parent directory. If no such
## file is found in the tree, jlenv will use the global Julia version
## specified with `jlenv global'. A version specified with the
## `JLENV_VERSION' environment variable takes precedence over local
## and global versions.
##
## <version> should be a string matching a Julia version known to jlenv.
## The special version string `system' will use your default system Julia.
## Run `jlenv versions' for a list of available Julia versions.
{
  # Provide jlenv completions
  if [ "$1" = "--complete" ]; then
    echo --unset
    echo system
    exec com_versions --bare
  fi

  JLENV_VERSION="$1"

  if [ "$JLENV_VERSION" = "--unset" ]; then
    rm -f .julia-version
  elif [ -n "$JLENV_VERSION" ]; then
    com_version-file-write .julia-version "$JLENV_VERSION"
  else
    version_file="$(com_version-file "$PWD")"
    if [ -f "${version_file}" ]
    then
      com_version-file-read "$version_file"
    else
      echo "jlenv: no local version configured for this directory" >&2
      ret=-$E_NO_VRSN_FL
      result="Searched: "$1"/.julia-version ... /.julia-version"
      return $ret
    fi
  fi
}
