#!/usr/bin/env bash
# Summary: List hook scripts for a given jlenv command
# Usage: jlenv hooks <command>

set -e
[ -n "$JLENV_DEBUG" ] && set -x

# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

JLENV_COMMAND="$1"
if [ -z "$JLENV_COMMAND" ]; then
  jlenv-help --usage hooks >&2
  exit 1
fi

IFS=: hook_paths=($JLENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$JLENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
