#!/usr/bin/env bash
# Summary: List all Julia versions available to jlenv
# Usage: jlenv versions [--bare] [--skip-aliases]
#
# Lists all Julia versions found in `$JLENV_ROOT/versions/*'.

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -x

unset bare
unset skip_aliases

# Provide jlenv completions
for arg; do
  case "$arg" in
  --complete )
    echo --bare
    echo --skip-aliases
    exit ;;
  --bare ) bare=1 ;;
  --skip-aliases ) skip_aliases=1 ;;
  * )
    jlenv-help --usage versions >&2
    exit 1
    ;;
  esac
done

versions_dir="${JLENV_ROOT}/versions"

if [ -d "$versions_dir" ]; then
  versions_dir="$(resolve_path "$versions_dir")"
fi

if [ -n "$bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(jlenv-version-name || true)"
  include_system="1"
fi

num_versions=0

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(jlenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
  num_versions=$((num_versions + 1))
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && JLENV_VERSION=system jlenv-which julia >/dev/null 2>&1; then
  print_version system
fi

shopt -s nullglob
for path in "$versions_dir"/*; do
  if [ -d "$path" ]; then
    if [ -n "$skip_aliases" ] && [ -L "$path" ]; then
      target="$(resolve_path "$path")"
      [ "${target%/*}" != "$versions_dir" ] || continue
    fi
    print_version "${path##*/}"
  fi
done
shopt -u nullglob

if [ "$num_versions" -eq 0 ] && [ -n "$include_system" ]; then
  echo "Warning: no Julia detected on the system" >&2
  exit 1
fi
