#!/usr/bin/env bash
# Summary: Explain how the current Julia version is set

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -x

unset JLENV_VERSION_ORIGIN

OLDIFS="$IFS"
IFS=$'\n' scripts=(`jlenv-hooks version-origin`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -n "$JLENV_VERSION_ORIGIN" ]; then
  echo "$JLENV_VERSION_ORIGIN"
elif [ -n "$JLENV_VERSION" ]; then
  echo "JLENV_VERSION environment variable"
else
  jlenv-version-file
fi
