#!/usr/bin/env bash
jlenv_sh-rehash()
## Summary: Rehash jlenv shims (run this after installing executables)
##
## Usage: jlenv [<opts>] rehash
##
## Installs shims for all Julia executables known to jlenv (i.e.,
## `~/.jlenv/versions/*/bin/*`). Run this command after you install a new
## version of Julia, or install a gem that provides executables.
{
# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  exec com_rehash --complete
fi

shell="$(basename "${JLENV_SHELL:-$SHELL}")"

# When jlenv shell integration is enabled, delegate to com_rehash,
# then tell the shell to empty its command lookup cache.
com_rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
}
