#!/usr/bin/env bash
jlenv_exec()
## Summary: Run an executable with the selected Julia version
##
## Usage: jlenv exec <command> [arg1 arg2...]
##
## Runs an executable by first preparing PATH so that the selected Julia
## version's `bin' directory is at the front.
{
# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  exec com_shims --short
fi

JLENV_VERSION="$(com_version-name)"
JLENV_COMMAND="$1"
# Return if the was a problem during com_version-name 
if [ -z "${JLENV_VERSION}" ]
then 
  ret=-$E_NO_VRSN_NMBR
  return $ret
fi

if [ -z "$JLENV_COMMAND" ]; then
  echo 'deprecated: jlenv-help --usage exec >&2'
  exit 1
fi

export JLENV_VERSION
JLENV_COMMAND_PATH="$(com_which "$JLENV_COMMAND")"
JLENV_BIN_PATH="${JLENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=($(com_hooks exec))
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$JLENV_VERSION" != "system" ]; then
  export PATH="${JLENV_BIN_PATH}:${PATH}"
fi
exec -a "$JLENV_COMMAND" "$JLENV_COMMAND_PATH" "$@"
}
