#!/usr/bin/env bash
jlenv_version_file_write()
## Summary Write given <semver> number to given <file>
##
## Usage: jlenv [<opts>] version-file-write <file> <semver>
##
## At least one of ${JLENV_VERSION} and ${JLENV_VERSION_FILE}need to
## be set.
## This is a low level utility command.  Primarily used internally by jlenv.
## General users are unlikely to use this command.
{
JLENV_VERSION_FILE="$1"
JLENV_VERSION="$2"

if [ -z "${JLENV_VERSION}" ] || [ -z "${JLENV_VERSION_FILE}" ]; then
  $(command jlenv2 help version-file-write)
  ret=-$E_HLP
  result='Use $(jlenv2 help) to print all help options.'
  return $ret
fi

# Make sure the specified version is installed.
com_prefix "$JLENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$JLENV_VERSION" > "$JLENV_VERSION_FILE"
ret=$GSU_SUCCESS
result="$JLENV_PREFIX_PATH"
return $ret
}
