#!/usr/bin/env bash

com_version()
##
##
## Show the current Julia version and how it was selected.
##
## Usage: jlenv version []
##
## To obtain only the version string, use $(jlenv version-name).
## Any arguments to this function are ignored.
##
## Options:
##
##      -v: Enable verbose mode
##      -c: Enable cron mode
##      -n: Enable no-color mode
##
## Warning: This subcommand may cause the top most line of your
## terminal to disappear and may cause DATA LOSS in your scrollback
## buffer. Use with caution.
{
  # no arguments allowed
  gsu_check_arg_count $# 0 0 
  # gsu_err_msg "${result}"
  ((ret < 0)) && return
  
  # Options
  # [c]ron, [n]o-color, [v]erbose
  gsu_getopts 'cnv'
  eval "$result"
  ((ret < 0)) && return

  # The verbose option variable
  if [ "$o_v" = 'true' ]; then 
    printf '%s (set by %s)\n' "$("${gsu_dir}/jlenv-version-name")" "$("${gsu_dir}/jlenv-version-origin")"
  else
    printf '%s (set by %s)\n' "$("${gsu_dir}/jlenv-version-name")" "$("${gsu_dir}/jlenv-version-origin")"
  fi
  ret=$GSU_SUCCESS
}
