#!/usr/bin/env bash
jlenv_hooks() 
## List hook scripts for a given jlenv command
##
## Usage: jlenv [<opts>] hooks <command>
##
## Hooks are bash scripts named `HOOK_NAME/*.bash`, where "HOOK_NAME" is one of:
## * `exec`
## * `rehash`
## * `version-name`
## * `version-origin`
## * `which`
##
## Hooks are looked for in ${JLENV_HOOK_PATH}, which is composed of:
## 1. `$JLENV_HOOK_PATH` (external value)
## 2. `$JLENV_ROOT/jlenv.d`
## 3. `/usr/local/etc/jlenv.d`
## 4. `/etc/jlenv.d`
## 5. `/usr/lib/jlenv/hooks`
## 6. `$JLENV_ROOT/plugins/*/etc/jlenv.d`
##
## Hook scripts are executed at specific points during jlenv operation.
## They provide a low-level entry point for integration with jlenv's functionality.
## To get a better understanding of the possibilities with hooks, read the source
## code of jlenv's hook-enabled commands listed above.
{   
    # Provide jlenv completions
    if [ "$1" = "--complete" ]; then
        echo exec
        echo rehash
        echo version-name
        echo version-origin
        echo which
        exit
    fi

    JLENV_COMMAND="$1"
    if [ -z "$JLENV_COMMAND" ]; then
        echo 'deprecated: jlenv-help --usage hooks >&2'
        exit 1
    fi

    IFS=: hook_paths=($JLENV_HOOK_PATH)

    # TODO: Skip duplicate paths
    # The following reorders the JLENV_HOOK_PATH - which we don't want to do....
    # JLENV_HOOK_PATH=`echo $JLENV_HOOK_PATH | tr ':' '\n' | sort | uniq | tr '\n' ':'`
    # for a path utility that only adds if not present see:
    # https://unix.stackexchange.com/a/110045/251061
    # For the following 1-liner:
    # echo "$JLENV_HOOK_PATH" | plit on :|sort -k2 | uniq -f1 | sort -k1 | cut -f2-| join back with :
    # See. 
    # https://unix.stackexchange.com/a/194790/251061
    shopt -s nullglob
    for path in "${hook_paths[@]}"; do
        if [ ! -d "$path" ]; then continue; fi
        for script in "${path}/${JLENV_COMMAND}"/*.bash; do
            f="$(resolve_path "${script}")"
            f="$(resolve_link "${f}")"
            echo $f
        done
    done
    shopt -u nullglob
}