#!/usr/bin/env bash
#
# Summary: Rehash jlenv shims (run this after installing executables)
#
# Usage: jlenv [<opts>] rehash
#
# Installs shims for all Julia executables known to jlenv (i.e.,
# `~/.jlenv/versions/*/bin/*`). Run this command after you install a new
# version of Julia, or install a gem that provides executables.

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -x

# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  exec jlenv-rehash --complete
fi

shell="$(basename "${JLENV_SHELL:-$SHELL}")"

# When jlenv shell integration is enabled, delegate to jlenv-rehash,
# then tell the shell to empty its command lookup cache.
jlenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
