#!/usr/bin/env bash
jlenv_root()
## Display the root directory where versions and shims are kept
##
## Usage: 
##
## Resolves relative path elements to their absolute value.
## Does not resolve symlinks.
{
echo "${JLENV_ROOT}"
}
