#!/usr/bin/env bash
jlenv_global()
# Summary: Set or show the global Julia version
#
# Usage: jlenv [<opts>] global <semver>
#
# Sets the global Julia version. You can override the global version at
# any time by setting a directory-specific version with `jlenv local'
# or by setting the `JLENV_VERSION' environment variable.
#
# <semver> should be a string matching a Julia version known to jlenv.
# The special version string `system' will use your default system Julia.
# Run `jlenv versions' for a list of available Julia versions.
{
# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec com_versions --bare
fi

JLENV_VERSION="$1"

if [ -n "$JLENV_VERSION" ]; then
  com_version-file-write "${JLENV_ROOT}/version" "$JLENV_VERSION"
else
  JLENV_VERSION_FILE="${JLENV_ROOT}/version"
  com_version-file-read "$JLENV_VERSION_FILE" || echo system
fi
}
