#!/usr/bin/env bash

_whence() {
  local command="$1"
  com_versions --bare | while read version; do
    path="$(jlenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

jlenv_whence()
## Summary: List Julia version numbers that contain the given executable
##
## Usage: jlenv [<opts>] whence [--path] <command>
##
## The list is a simple version list, similar to $(jlenv versions --bare).
## 
## Options:
##   --path  Print the path to the version(s) of Julia.
{
# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec jlenv-shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

JLENV_COMMAND="$1"
if [ -z "$JLENV_COMMAND" ]; then
  echo 'deprecated: jlenv-help --usage whence >&2'
  exit 1
fi

result="$(_whence "$JLENV_COMMAND")"
[ -n "$result" ] && echo "$result"

}