#!/usr/bin/env bash
jlenv_version_file_read()
## Summary Read version number from given <file>
##
## Usage: jlenv [<opts>] version-file-read <file>
##
## This is a low level utility command.  Primarily used internally by jlenv.
## General users are unlikely to use this command.
##
## For full documentation, see: https://github.com/jlenv/jlenv#readme
{
  VERSION_FILE="$1"

  if [ -e "$VERSION_FILE" ]; then
    # Read the first non-whitespace word from the specified version file.
    # Be careful not to load it whole in case there's something crazy in it.
    IFS="${IFS}"$'\r'
    words=( $(cut -b 1-1024 "$VERSION_FILE") )
    version="${words[0]}"
    #TODO: semantic version number check.
    if [ -n "$version" ]; then
      echo "$version"
      ret=$GSU_SUCCESS
      result="$version"
      return $ret
    fi
    ret=-$E_NO_VRSN_NMBR
    result="The file $VERSION_FILE contained: <start>${words[@]}<end>."
    return
  fi
  ret=-$E_NO_VRSN_FL
  result="The file $VERSION_FILE does not exist."
  return
}