#!/usr/bin/env bash
#
# Summary: Set or show the global Julia version
#
# Usage: jlenv global <version>
#
# Sets the global Julia version. You can override the global version at
# any time by setting a directory-specific version with `jlenv local'
# or by setting the `JLENV_VERSION' environment variable.
#
# <version> should be a string matching a Julia version known to jlenv.
# The special version string `system' will use your default system Julia.
# Run `jlenv versions' for a list of available Julia versions.

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -x

# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec jlenv-versions --bare
fi

JLENV_VERSION="$1"
JLENV_VERSION_FILE="${JLENV_ROOT}/version"

if [ -n "$JLENV_VERSION" ]; then
  jlenv-version-file-write "$JLENV_VERSION_FILE" "$JLENV_VERSION"
else
  jlenv-version-file-read "$JLENV_VERSION_FILE" || echo system
fi
