#!/usr/bin/env bash
#
# Summary Write given <semver> number to given <file>
#
# Usage: jlenv [<opts>] version-file-write <file> <semver>
#
# This is a low level utility command.  Primarily used internally by jlenv.
# General users are unlikely to use this command.

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -o xtrace

JLENV_VERSION_FILE="$1"
JLENV_VERSION="$2"

if [ -z "$JLENV_VERSION" ] || [ -z "$JLENV_VERSION_FILE" ]; then
  jlenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
jlenv-prefix "$JLENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$JLENV_VERSION" > "$JLENV_VERSION_FILE"
