#!/usr/bin/env bash
jlenv_shims()
## Summary: List existing jlenv shims
##
## Usage: jlenv [<opts>] shims [--short]
##
## Prints the list of shims installed for the current version of Julia.
##
## Options:
##    --short  Print the executable name only, with no path.
{

# Provide jlenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${JLENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
}
