#!/usr/bin/env bash
#
# Summary: Show the current Julia version and its origin
#
# Usage: jlenv [<opts>] version
#
# Shows the currently selected Julia version and how it was
# selected. 
# To obtain only the version string, use $(jlenv version-name).

# Import functions shared between jlenv scripts and plugins.
# Function specific to each jlenv-<command> script are:
# - script_usage
# - main "$@" which calls
#    1. script_init "$@"
#    2. script_defaults
#    3. parse_cmds "$@"
# - `jlevn_<command>` holds functional logic and is called by `parse_cmds`
source jlenv-shared

set -e
[ -n "$JLENV_DEBUG" ] && set -o xtrace

echo "$(jlenv-version-name) (set by $(jlenv-version-origin))"
