---
title: `jlenv` Julia version management for your application
email: mark@taqtiqa.com
description: > # this means to ignore newlines until "baseurl:"
  Build, install and manage multiple versions of [Julia](https://www.julialang.org/).
github_username:  jlenv
include_related_posts: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
